import "./globals.css";
import { Poppins } from "next/font/google";
import Script from "next/script"; // ✅ ADD THIS
import { AuthProvider } from "@/contexts/login.context";
import { TestProvider } from "@/contexts/test.context";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Skylite educations - Modren testing solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">

        {/* ✅ OpenCV.js (FREE, required for scanImage) */}
        <Script
          src="https://docs.opencv.org/4.x/opencv.js"
          strategy="beforeInteractive"
        />
        <TestProvider>
        <AuthProvider>
          {children}
        </AuthProvider>
        </TestProvider>
      </body>
    </html>
  );
}
